version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
      - ./vendor:/var/www/vendor:cached
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: php-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www:cached
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: php-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: php-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local 